#spring.application.name=department-service


//spring.application.name=Backendproject
server.port=8089
spring.datasource.url=jdbc:mysql://localhost:3306/department_db 
spring.datasource.password=naveen@123

//hibnernate will automatically create the databases with this ddl auto update 
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root



spring.application.name =DEPARTMENT-SERVICE
eureka.instanse.client.serverUrl.defaultZone = http://localhost:8761/eureka/




